#!/usr/bin/env python3
"""Generate a static roster.html from recruits.json"""
import json
import os

script_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
json_path = os.path.join(script_dir, "data", "recruits.json")
html_path = os.path.join(script_dir, "roster.html")

with open(json_path) as f:
    recruits = json.load(f)

if not recruits:
    print("No recruits yet, nothing to render")
    exit(0)

cards = []
ROLE_CLASS = {"DPS": "role-damage", "Tank": "role-tank", "Support": "role-support"}

for r in reversed(recruits[-50:]):
    rc = ROLE_CLASS.get(r.get("role", "DPS"), "role-damage")
    tag = r.get("tag", "Unknown")
    hero = r.get("hero", "?")
    hero_img = r.get("heroImg", "")
    wr = r.get("winRate", "?%")
    deaths = r.get("deaths", "?")
    kda_val = r.get("kda", "?")
    bstat = r.get("bonusStat", "???")
    blabel = r.get("bonusLabel", "Stat")
    spec = r.get("specialty", "Fresh meat")
    cards.append(f'''        <div class="roster-card {rc}">
          <img class="card-img" src="{hero_img}" alt="{hero}" loading="lazy" />
          <div class="card-body">
            <div class="player-name">{tag}</div>
            <div class="player-role">{r.get("role", "DPS")} \u2014 {hero}</div>
            <div class="player-stats">
              <div class="ps-item"><strong>{wr}</strong>Win Rate</div>
              <div class="ps-item"><strong>{deaths}</strong>Avg Deaths</div>
              <div class="ps-item"><strong>{kda_val}</strong>KDA</div>
              <div class="ps-item"><strong>{bstat}</strong>{blabel}</div>
            </div>
            <div class="specialty"><span>Specialty:</span> {spec}</div>
          </div>
        </div>''')

html = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Generated Roster \u2014 Team Throw</title>
  <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Rajdhani:wght@400;500;600;700&display=swap" rel="stylesheet" />
  <style>
    *,*::before,*::after{margin:0;padding:0;box-sizing:border-box}
    :root{--black:#0d0d0d;--red:#c0392b;--red-dark:#8a1e1e;--red-glow:rgba(192,57,43,0.4);--white:#ffffff;--gray:#888888;--gray-dark:#1a1a1a;--font-display:'Bebas Neue',sans-serif;--font-body:'Rajdhani',sans-serif}
    body{font-family:var(--font-body);background:var(--black);color:var(--white);padding:2rem}
    h1{font-family:var(--font-display);text-align:center;font-size:3rem;letter-spacing:4px;color:var(--red);margin-bottom:0.5rem}
    .sub{text-align:center;color:var(--gray);margin-bottom:2rem;letter-spacing:2px;text-transform:uppercase;font-size:0.85rem}
    .count{text-align:center;color:#555;margin-bottom:2rem;font-size:0.9rem}
    .roster-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:2rem;max-width:1200px;margin:0 auto}
    .roster-card{background:var(--gray-dark);border:1px solid rgba(255,255,255,0.03);overflow:hidden;transition:all 0.4s}
    .roster-card:hover{border-color:var(--red);transform:translateY(-4px);box-shadow:0 8px 30px rgba(192,57,43,0.1)}
    .roster-card .card-img{width:100%;height:260px;object-fit:cover;object-position:center top;background:linear-gradient(180deg,#1a1a1a 0%,#0d0d0d 100%);opacity:0.85}
    .roster-card .card-body{padding:1.5rem}
    .player-name{font-family:var(--font-display);font-size:1.6rem;letter-spacing:2px;color:var(--white)}
    .player-role{display:inline-block;font-weight:600;font-size:0.75rem;letter-spacing:2px;text-transform:uppercase;color:var(--gray);background:rgba(255,255,255,0.03);padding:0.2rem 0.8rem;margin-top:0.3rem}
    .player-stats{margin-top:1rem;display:grid;grid-template-columns:1fr 1fr;gap:0.5rem}
    .ps-item{font-size:0.8rem;color:var(--gray);letter-spacing:0.5px}
    .ps-item strong{color:var(--red);font-weight:600;display:block;font-size:1rem}
    .specialty{margin-top:1rem;padding-top:1rem;border-top:1px solid rgba(255,255,255,0.05);font-size:0.85rem;color:var(--gray);text-transform:uppercase;letter-spacing:1px}
    .specialty span{color:var(--red);font-weight:600}
    .role-damage{border-left:3px solid #e74c3c}
    .role-tank{border-left:3px solid #3498db}
    .role-support{border-left:3px solid #f1c40f}
    .footer{text-align:center;margin-top:3rem;color:#444;font-size:0.8rem;letter-spacing:1px}
  </style>
</head>
<body>
  <h1>TEAM THROW</h1>
  <div class="sub">Full Roster \u2014 Auto-generated</div>
  <div class="count">""" + str(len(recruits)) + """ recruit(s) on file</div>
  <div class="roster-grid">
""" + "\n".join(cards) + """
  </div>
  <div class="footer">Generated by GitHub Actions from recruits.json</div>
</body>
</html>"""

with open(html_path, "w") as f:
    f.write(html)
print(f"Generated roster.html with {len(recruits)} recruits")
